# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 18:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 1, 18, 45, 24, 656715, tzinfo=utc)),
        ),
    ]
